### PR TITLE
Some backend optimizations

### PR DESCRIPTION
**Pull request by RedCrafter07**
This Pull Request includes:
- Reformatting
- Using middleware (app.use()) for less usage of apiNeedsLogin
- add email & password to environment variables
- Add page title
- Add WIP Notice on logged in home page (client/src/routes/lHome.tsx)
- Some other optimizations

This will simplify your backend functionality and reduce the amount of code you have to write for the API. Hope it helps :)

### CODE REVIEW

**Comment by FishingHacks** [comment]
Did you test it?

**Comment by RedCrafter07** [comment]
I did.

**Comment by RedCrafter07** [comment]
I wouldn't submit this PR if I wouldn't test it

**Comment by FishingHacks** [comment]
It did work for you, but idk how to merge it without recoding the server/index.ts, as it doesn't include the database change

**Comment by FishingHacks** [comment]
I'll look what i can do

**Comment by RedCrafter07** [comment]
Well, you'd have to push frequently so it wouldn't conflict. It doesn't conflict with the current repo.

**Comment by FishingHacks** [comment]
Yes it doesn't, but because I changed types from enmap to array, the accessing changed...

**Review by FishingHacks — COMMENTED** [review]
merged

**Pull request merged**
